// Export all components
export { default as VileadSidebar } from './VileadSidebar'
export { default as Header } from './Header'
export { default as Dashboard } from './Dashboard'
export { default as SalesManagement } from './SalesManagement'
export { default as TaskManagement } from './TaskManagement'
export { default as CompanyManagement } from './CompanyManagement'
export { default as ReportsManagement } from './ReportsManagement'
export { default as SettingsManagement } from './SettingsManagement'
export { default as VileadsChatbot } from './VileadsChatbot'
export { default as AccountantDashboard } from './AccountantDashboard'
export { default as AIAssistant } from './AIAssistant'
export { default as AISuggestionsTab } from './AISuggestionsTab'
// export { default as ChatbotAssistant } from './ChatbotAssistant'
export { default as ChatbotAssistantNew } from './ChatbotAssistantNew'
export { DepartmentModal, TeamModal } from './DepartmentTeamModals'
// Legacy components - kept for reference
// export { default as LeadsManagement } from './LeadsManagement'
// export { default as CustomersManagement } from './CustomersManagement'
// export { default as DealsManagement } from './DealsManagement'
// export { default as VileadLeadsKanban } from './VileadLeadsKanban'
export { default as DashboardFilters } from './DashboardFilters'